import { test, expect } from '@playwright/test'

test('hover expands code outside the scrolling card and restores its layout', async ({ page }) => {
  await page.goto('/lesson/scene-anatomy/what-the-camera-sees')
  const block = page.locator('.code-block').first()
  await expect(block).toBeVisible()
  await page.evaluate(() => document.fonts.ready)
  await block.scrollIntoViewIfNeeded()
  const before = await block.boundingBox()
  const anchor = page.locator('.code-block-anchor').first()
  const anchorBefore = await anchor.boundingBox()
  await block.hover()
  await expect(block).toHaveAttribute('popover', 'manual')
  const expanded = await block.boundingBox()
  expect(expanded.width).toBeGreaterThan(before.width)
  expect(expanded.x + expanded.width).toBeLessThanOrEqual(1440 - 12)
  expect(await anchor.boundingBox()).toEqual(anchorBefore)
  await page.mouse.move(expanded.x + expanded.width - 10, expanded.y + 10)
  await expect(block).toHaveAttribute('popover', 'manual')
  expect(await block.evaluate((element) => {
    const rect = element.getBoundingClientRect()
    return element.contains(document.elementFromPoint(rect.right - 10, rect.top + 10))
  })).toBe(true)
  await page.mouse.move(1400, 980)
  await expect(block).not.toHaveAttribute('popover')
  expect((await block.boundingBox()).width).toBe(before.width)
  await block.locator('pre').focus()
  await expect(block).toHaveAttribute('popover', 'manual')
  await page.keyboard.press('Escape')
  await expect(block).not.toHaveAttribute('popover')
})
